# Generated by Django 5.1.7 on 2025-03-24 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
