# Generated by Django 5.1.7 on 2025-04-05 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_team_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='sportmonks_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
