# Generated by Django 5.1.7 on 2025-04-05 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_team_sportmonks_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='sportmonks_id',
            new_name='api_football_id',
        ),
    ]
