# Generated by Django 5.1.7 on 2025-04-08 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0004_rename_sportmonks_id_team_api_football_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='api_football_id',
            new_name='api_football_team_id',
        ),
    ]
