# Generated by Django 5.1.7 on 2025-04-12 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0005_rename_api_football_id_team_api_football_team_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='api_football_team_id',
        ),
    ]
