# Generated by Django 5.1.7 on 2025-04-12 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0006_remove_team_api_football_team_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='api_football_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
