# Generated by Django 5.1.7 on 2025-04-12 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0007_team_api_football_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='api_league_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
