# Generated by Django 5.1.7 on 2025-04-13 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0009_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='background_image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
