# Generated by Django 5.1.7 on 2025-04-25 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0010_team_background_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='football_data_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
