# Generated by Django 5.1.7 on 2025-04-25 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0011_team_football_data_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='football_data_code',
        ),
        migrations.AddField(
            model_name='team',
            name='football_data_league_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='football_data_team_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
